%%metro title: GenAbu RNA-seq Analysis Pipeline
%%metro style: nfcore

%%metro line: fastq | FASTQ input | #a16e02
%%metro line: sra | SRA input | #df0b0b
%%metro line: paper | Paper accession | #ffdd00
%%metro line: with_sra | SRA-derived reads | #fdad00
%%metro line: main | Analysis workflow | #0ee20e
%%metro line: reference | Reference input | #0a790a

%%metro files: fastq_input | FASTQ | FASTQ input
%%metro files: sra_input | SRA | SRA input
%%metro files: paper_input | Paper | Paper accession
%%metro files: genabu_table | csv | Gene abundance
%%metro file: multiqc_report | MultiQC | MultiQC report
%%metro files: salmon_index | Salmon index | Salmon index
%%metro files: reference_gtf | GTF | Reference annotation

%%metro off_track: genabu_table

%%metro grid: input | 0,0
%%metro grid: preprocessing | 1,0
%%metro grid: reference | 1,1
%%metro grid: quantification | 2,0
%%metro grid: reporting | 3,0
%%metro grid: reporting_genabu | 3,1

graph LR

    subgraph input [Input]

        fastq_input[ ]
        sra_input[ ]
        paper_input[ ]

        router[Input Router]
        validator[Input Validator]
        paper_accessions[Paper Accessions]
        sra[SRA Input]

        fastq_input -->|fastq| router
        sra_input -->|sra| router
        paper_input -->|paper| router
        router -->|fastq| validator
        router -->|sra| validator
        router -->|paper| paper_accessions
        validator -->|sra| sra
        paper_accessions -->|paper| sra
    end

    subgraph preprocessing [Pre-processing]

        falco[Falco]
        cutadapt[Cutadapt]
        falco_trim[Falco Trim]

        falco -->|main| cutadapt
        cutadapt -->|main| falco_trim
    end

    subgraph quantification [Quantification]

        salmon[Salmon]
        gene_abundance[Gene Abundance]

        salmon -->|main| gene_abundance

    end

    subgraph reference [Reference preparation]

        salmon_index[Salmon index]
        reference_gtf[Reference gtf]

    end

    subgraph reporting [Reporting QC]

        multiqc[MultiQC]
        multiqc_report[ ]

        multiqc -->|main| multiqc_report

    end

    subgraph reporting_genabu [Reporting GA]

        gene_name[Name mapping]
        genabu_table[ ]

        gene_name -->|main| genabu_table

    end

    validator -->|fastq| falco
    sra -->|with_sra| falco
    falco_trim -->|main| salmon
    salmon_index -->|reference| salmon
    reference_gtf -->|reference| salmon
    gene_abundance -->|main| multiqc
    gene_abundance -->|main| gene_name