name: Nextflow tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: latest-stable

      - name: Install nf-test
        uses: nf-core/setup-nf-test@v1
        with:
          version: 0.9.5

      - name: Run pipeline smoke test
        run: nextflow run . -profile test -stub-run

      - name: Run nf-test suite
        run: nf-test test --tag ci --ci