name: Nextflow test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: latest-stable

      - name: Run test profile
        run: nextflow run . -profile test